opt_in_rules:
  - anyobject_protocol
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon
  - contains_over_first_not_nil
  - convenience_type
  - empty_count
  - empty_enum_arguments
  - empty_string
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name
  - first_where
  - force_cast
  - force_try
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - last_where
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - legacy_random
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - operator_usage_whitespace
  - private_action
  - private_outlet
  - reduce_into
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - strong_iboutlet
  - trailing_newline
  - type_name
  - unneeded_parentheses_in_closure_argument
  - unused_closure_parameter
  - unused_optional_binding
  - vertical_whitespace
  - void_return
  - custom_rules

disabled_rules:
  - todo
  - identifier_name
  
excluded:
  - build
  - gems
  - Pods

file_name:
  excluded: ["Assets.swift", "Storyboard.swift", "Strings.swift"]

colon:
  apply_to_dictionaries: false

indentation: 2

line_length:
  error: 120

type_body_length:
  warning: 400

function_body_length:
  warning: 50

#custom_rules:
#  swiftgen_assets:
#    name: "SwiftGen Assets"
#    regex: '(UIImage|UIColor)(\.init)?\(named: ?"?.+"?(, ?in:.+?, ?compatibleWith:.+?)?\)|#imageLiteral\(resourceName: ?".+"\)'
#    message: "Use Assets.<asset> instead"
#    severity: error
#  swiftgen_colors:
#    name: "SwiftGen Colors"
#    regex: '(UIColor(\.init)?|#colorLiteral)\(((red|displayP3Red):.+?,green:.+?,blue:.+?,alpha:.+?)|(white:.+?,alpha:.+?)|(hue:.+?,saturation:.+?,brightness:.+?,alpha:.+?)\)'
#    message: "Use Colors.<color> instead"
#    severity: error
#  swiftgen_storyboards:
#    name: "SwiftGen Storyboard Scenes"
#    regex: '(UIStoryboard\(name: ?"?.+"?, ?bundle:.+\))|(instantiateViewController\(withIdentifier:.+?\))|(instantiateInitialViewController\(\))'
#    message: "Use StoryboardScene.<storyboad>.<scene>.instantiate() instead"
#    severity: error
#  swiftgen_strings:
#    name: "SwiftGen Strings"
#    regex: 'NSLocalizedString'
#    message: "Use Strings.key instead"
#    severity: error
